import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/features/layout/components/nav-bar";
import { Playfair_Display, DM_Sans } from "next/font/google";
import { ThemeProvider } from "next-themes"; // o tu ruta de importación

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  variable: "--font-playfair",
  display: "swap",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  style: ["normal", "italic"],
  variable: "--font-dm-sans",
  display: "swap",
});

/* ─────────────────────────────────────────────────────────
   METADATA
───────────────────────────────────────────────────────── */
export const metadata: Metadata = {
  title: {
    default: "Kriste Reyes — Makeup & Beauty",
    template: "%s | LUXÉ",
  },
  icons: {
    icon: "/favicon.ico", // Ruta relativa a la carpeta public
    // Puedes agregar más formatos si lo deseas:
    // shortcut: "/shortcut-icon.png",
    // apple: "/apple-icon.png",
  },
  description:
    "Fórmulas luminosas para cada tono de piel. Descubre nuestra colección de makeup premium.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${playfair.variable} ${dmSans.variable} h-full antialiased scrollbar-none [&::-webkit-scrollbar]:hidden`}
    >
      <body className="min-h-full flex flex-col no-scrollbar">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
